// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsMeRc5Qu2nwjtZCQ8X27RqgSwWICV1uc',
    appId: '1:144723666872:web:0579c4ef8ea81b7565d14d',
    messagingSenderId: '144723666872',
    projectId: 'map-90396',
    authDomain: 'map-90396.firebaseapp.com',
    storageBucket: 'map-90396.firebasestorage.app',
    measurementId: 'G-23NPXFL8YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEQIqy-NOcEAoxEa0FxsubkL0LTXR0mzw',
    appId: '1:144723666872:android:9c2b571205152e6665d14d',
    messagingSenderId: '144723666872',
    projectId: 'map-90396',
    storageBucket: 'map-90396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRHGm_1xKbllGwG8VRJAZVjFsgEssKWLU',
    appId: '1:144723666872:ios:5fc82cf8d047a74c65d14d',
    messagingSenderId: '144723666872',
    projectId: 'map-90396',
    storageBucket: 'map-90396.firebasestorage.app',
    iosBundleId: 'com.example.googlemap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRHGm_1xKbllGwG8VRJAZVjFsgEssKWLU',
    appId: '1:144723666872:ios:5fc82cf8d047a74c65d14d',
    messagingSenderId: '144723666872',
    projectId: 'map-90396',
    storageBucket: 'map-90396.firebasestorage.app',
    iosBundleId: 'com.example.googlemap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsMeRc5Qu2nwjtZCQ8X27RqgSwWICV1uc',
    appId: '1:144723666872:web:7ac7561646f9316e65d14d',
    messagingSenderId: '144723666872',
    projectId: 'map-90396',
    authDomain: 'map-90396.firebaseapp.com',
    storageBucket: 'map-90396.firebasestorage.app',
    measurementId: 'G-C0B77PKR59',
  );
}
